language: node_js

node_js:
  - 10

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: surge
  project: ./build/
  domain: gentle-rat.surge.sh
  skip_cleanup: true
